/**
 * File Writer — takes Claude's generated files and writes them to the filesystem
 * via the MCP Client (so the Tester Agent can also read them back).
 */

import type { GeneratedFile } from "./builderAgent.js";
import type { MCPClient } from "./mcpClient.js";

export class FileWriter {
  constructor(private mcp: MCPClient) {}

  /**
   * Write all files generated by the Builder Agent to the workspace.
   * Returns the paths that were successfully written.
   */
  async writeFiles(files: GeneratedFile[]): Promise<string[]> {
    const written: string[] = [];

    for (const file of files) {
      console.log(`[FileWriter] Writing: ${file.path}`);
      const result = await this.mcp.writeFile(file.path, file.content);

      if (result.isError) {
        console.error(`[FileWriter] ERROR writing ${file.path}: ${result.output}`);
      } else {
        written.push(file.path);
        console.log(`[FileWriter] ✓ ${file.path}`);
      }
    }

    return written;
  }
}
